##Creating our own tensors

## Tensorflow Fundamentals

In [ ]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [ ]:
# Scalar number(Single number)
scalar = tf.constant(7)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=7>, 0)

In [ ]:
#Vector(1D)
vector = tf.constant([4,7])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 7], dtype=int32)>, 1)

In [ ]:
#Matrix(2D)
matrix = tf.constant([[4,7],[10,6]])
matrix,matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 4,  7],
        [10,  6]], dtype=int32)>, 2)

We will change dtype because int32/float32 use more memory

In [ ]:
##Tensors(ManyD)
tensors = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]], dtype= tf.int16)
tensors, tensors.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int16, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int16)>, 3)

We can also create tensors using variable,only difference is variable are mutable while tensors or not.Most of the time we the tensor which generate on it's own

In [ ]:
mutable_tensors = tf.Variable([10, 7])
imutable_tensors = tf.constant([12,8])

In [ ]:
mutable_tensors[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
imutable_tensors[0]

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
mutable_tensors[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 7], dtype=int32)>

In [ ]:
mutable_tensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 7], dtype=int32)>

imutable_tensors[0].assign(6)
error arrised:'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

##Setting seed and generating random number

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  7],
       [10,  6]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  7],
       [10,  6]], dtype=int32)>

In [ ]:
tf.random.shuffle(matrix, seed=42)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  6],
       [ 4,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(matrix, seed=42)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  6],
       [ 4,  7]], dtype=int32)>

Note: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence

In [ ]:
# Normal means normal distribution values
tf.random.normal(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ],
       [-2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ],
       [ 1.6994323 ,  0.28893656, -1.5066116 , -0.26454744]],
      dtype=float32)>

In [ ]:
tf.random.set_seed(42)
tf.random.normal(shape=(4,5,2))

<tf.Tensor: shape=(4, 5, 2), dtype=float32, numpy=
array([[[ 0.3274685 , -0.8426258 ],
        [ 0.3194337 , -1.4075519 ],
        [-2.3880599 , -1.0392479 ],
        [-0.5573232 ,  0.539707  ],
        [ 1.6994323 ,  0.28893656]],

       [[-1.5066116 , -0.26454744],
        [-0.59722406, -1.9171132 ],
        [-0.62044144,  0.8504023 ],
        [-0.40604794, -3.0258412 ],
        [ 0.9058464 ,  0.29855987]],

       [[-0.22561555, -0.7616443 ],
        [-1.891714  , -0.9384712 ],
        [ 0.77852213, -0.47338897],
        [ 0.97772694,  0.24694404],
        [ 0.20573747, -0.5256233 ]],

       [[ 0.32410017,  0.02545409],
        [-0.10638497, -0.6369475 ],
        [ 1.1603122 ,  0.2507359 ],
        [-0.41728497,  0.40125778],
        [-1.4145442 , -0.59318566]]], dtype=float32)>

## Other ways to make tensors

In [ ]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

We can also convert numpy array into tensors

In [ ]:
import numpy as np
Numpy_A = np.arange(1,25)

In [ ]:
Numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
tf.constant(Numpy_A, shape=[2,4,3])#Shape total match with number of element in the array

<tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

In [ ]:
tf.constant(Numpy_A, shape=[2,6,2])#Shape total match with number of element in the array

<tf.Tensor: shape=(2, 6, 2), dtype=int64, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])>

##Getting information from the tensors

In [ ]:
rand = tf.ones([3,4,5,6])

In [ ]:
rand

<tf.Tensor: shape=(3, 4, 5, 6), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1.

In [ ]:
tf.size(rand), rand.shape, rand.ndim, rand.dtype

(<tf.Tensor: shape=(), dtype=int32, numpy=360>,
 TensorShape([3, 4, 5, 6]),
 4,
 tf.float32)

In [ ]:
tf.size(rand).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=360>>

In [ ]:
3*4*5*6

360

In [ ]:
rand[1][1]

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
rand[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 6), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1., 1.]]]], dtype=float32)>

##Mathematical operation

In [ ]:
matrix = tf.constant([[10, 7],
                      [4, 8]])

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  8]], dtype=int32)>

In [ ]:
matrix+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [14, 18]], dtype=int32)>

In [ ]:
matrix-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-6, -2]], dtype=int32)>

In [ ]:
tf.multiply(matrix, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 40,  80]], dtype=int32)>

In [ ]:
matrix * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 40,  80]], dtype=int32)>

##Matrix Multiplication

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  8]], dtype=int32)>

In [ ]:
tf.matmul(matrix, matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 126],
       [ 72,  92]], dtype=int32)>

In [ ]:
matrix @ matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 126],
       [ 72,  92]], dtype=int32)>

In [ ]:
a = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [ ]:
b = tf.constant([[1,2,3],
                 [4,5,6]])

a @ b -Going to give error because of shape not matching

In [ ]:
a,b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

By using transpose and reshape we will acheive the result

In [ ]:
a @ tf.transpose(b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 14,  32],
       [ 32,  77],
       [ 50, 122]], dtype=int32)>

In [ ]:
a @ tf.reshape(b ,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]], dtype=int32)>

But the result are different lets look why result are different

In [ ]:
a,b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
tf.transpose(b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
tf.reshape(b, [3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

## Changing the data type of the tensors

In [ ]:
tensors = tf.constant([4, 5.5, 6])

In [ ]:
tensors

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4. , 5.5, 6. ], dtype=float32)>

In [ ]:
tf.cast(tensors, dtype=tf.float16)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([4. , 5.5, 6. ], dtype=float16)>

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  8]], dtype=int32)>

In [ ]:
tf.cast(matrix, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 4.,  8.]], dtype=float16)>

##Getting absolute value

In [ ]:
c = tf.constant([-4, -6, 8])
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-4, -6,  8], dtype=int32)>

In [ ]:
tf.abs(c)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 8], dtype=int32)>

# Let's look into min, max, sum, std, var

In [ ]:
scalar = tf.constant(np.random.randint(low = 1, high =100, size = 50))
scalar

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([85, 92, 28, 25, 74, 97, 78, 10, 93, 84, 96, 72, 52, 10, 14, 55, 69,
       15, 93, 55, 46, 93, 71, 46, 68, 16, 76, 95, 95, 73, 44, 71, 52, 34,
       67, 74, 26, 69, 76,  7, 50, 65, 56, 45, 12, 93, 77, 62, 26, 51])>

In [ ]:
tf.reduce_min(scalar)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
tf.reduce_max(scalar)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_sum(scalar)

<tf.Tensor: shape=(), dtype=int64, numpy=2933>

If you are not using cast method it shows error feel free check in the internet

In [ ]:
d = tf.cast(scalar, dtype=tf.float16)
tf.math.reduce_std(d)

<tf.Tensor: shape=(), dtype=float16, numpy=27.08>

In [ ]:
tf.math.reduce_variance(d)

<tf.Tensor: shape=(), dtype=float16, numpy=733.0>

## Finding a index of tensors

In [ ]:
e = tf.constant(np.random.random(50))

In [ ]:
e

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([6.38260256e-01, 6.56043757e-01, 2.71364809e-01, 1.20247275e-02,
       7.51481000e-01, 7.80876008e-01, 6.34587272e-01, 1.45044552e-01,
       8.58649694e-01, 8.94931670e-01, 9.51833986e-01, 9.31883289e-01,
       4.38287674e-01, 1.62209821e-02, 2.15394335e-02, 9.18508963e-01,
       3.91980450e-01, 9.89083988e-01, 1.10887260e-01, 2.58653130e-01,
       8.74192111e-02, 1.35267297e-01, 5.13309057e-01, 7.81194289e-01,
       8.49327146e-01, 4.48292384e-01, 7.87221785e-02, 8.92715603e-01,
       2.09121667e-01, 9.80340344e-01, 6.81366075e-01, 7.38683691e-01,
       3.39743723e-02, 5.16804137e-01, 4.11847216e-01, 2.77646483e-01,
       6.01545546e-01, 5.39277365e-01, 5.76632819e-01, 9.17289221e-01,
       3.93382836e-01, 5.22527357e-02, 3.18685058e-01, 2.92307385e-01,
       7.67657408e-02, 5.30441638e-05, 8.77090724e-01, 3.24649531e-01,
       9.75108977e-02, 5.82623197e-01])>

In [ ]:
tf.argmax(e)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
tf.argmin(e)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

## Squeeze(It will remove all one dimention)

In [ ]:
f = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))

In [ ]:
f.ndim, f.shape

(5, TensorShape([1, 1, 1, 1, 50]))

In [ ]:
sq = tf.squeeze(f)
sq

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([89, 37, 32, 90,  3, 41, 38, 49, 19, 91, 76,  5, 82, 37, 21, 19, 34,
        2, 10, 13, 62, 28, 37, 39,  5, 12, 12, 31, 13, 28, 43, 82, 96, 24,
       47, 87, 42, 92, 15, 21, 25, 55, 87, 88, 88, 56, 65, 82, 96, 96])>

In [ ]:
sq.ndim,sq.shape

(1, TensorShape([50]))

In [ ]:
f

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[89, 37, 32, 90,  3, 41, 38, 49, 19, 91, 76,  5, 82, 37, 21,
           19, 34,  2, 10, 13, 62, 28, 37, 39,  5, 12, 12, 31, 13, 28,
           43, 82, 96, 24, 47, 87, 42, 92, 15, 21, 25, 55, 87, 88, 88,
           56, 65, 82, 96, 96]]]]])>

## One hot encode

In [ ]:
b = [1, 2, 3, 4]

In [ ]:
tf.one_hot(b, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(b, depth=4, on_value="Mukesh", off_value="Lokesh")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Lokesh', b'Mukesh', b'Lokesh', b'Lokesh'],
       [b'Lokesh', b'Lokesh', b'Mukesh', b'Lokesh'],
       [b'Lokesh', b'Lokesh', b'Lokesh', b'Mukesh'],
       [b'Lokesh', b'Lokesh', b'Lokesh', b'Lokesh']], dtype=object)>

##Math operation

In [ ]:
g = tf.constant(np.arange(1,20,2))
g

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])>

In [ ]:
tf.square(g)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])>

In [ ]:
tf.sqrt(tf.cast(g, dtype=tf.float16))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([1.   , 1.732, 2.236, 2.646, 3.   , 3.316, 3.605, 3.873, 4.125,
       4.36 ], dtype=float16)>

Some time we have to cast value to get the output orelse error pop up.

## Lets play with variable tensors

In [ ]:
h = tf.Variable([5,7])
h

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
h.assign([5,6])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 6], dtype=int32)>

In [ ]:
h

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 6], dtype=int32)>

In [ ]:
h.assign_add([10, 10])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([15, 16], dtype=int32)>

## @tf function

In [ ]:
def function(x,y):
  return x*2 + y*3
 
x = tf.constant(np.arange(1,10,2))
y = tf.constant(np.arange(1,10,2))

function(x,y)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 5, 15, 25, 35, 45])>

In [ ]:
@tf.function
def function(x,y):
  return x*2 + y*3

function(x,y)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 5, 15, 25, 35, 45])>

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

##Checking GPU

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Jan  5 12:01:58 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8    27W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------